src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'string', length: 255)]
    private $alias;

    #[ORM\Column(type: 'string', length: 255)]
    private $subtitle;

    #[ORM\Column(type: 'text')]
    #[Assert\NotBlank(message: "Ce champ ne peut être vide")]

    private $content;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $photo;

    #[ORM\Column(type: 'datetime')]
    private $createdAt;

    #[ORM\Column(type: 'datetime')]
    private $updatedAt;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $deletedAt;

    #[ORM\ManyToOne(targetEntity: Categorie::class, inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private $category;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'articles')]
    private $author;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(string $subtitle): self
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?\DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    public function getCategory(): ?Categorie
    {
        return $this->category;
    }

    public function setCategory(?Categorie $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?UserInterface $author): self
    {
        $this->author = $author;

        return $this;
    }
}

src/Entity/Commentary.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\CommentaryRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;

#[ORM\Entity(repositoryClass: CommentaryRepository::class)]
class Commentary
{
    // un trait est une sorte de class de PHP qui vous sert à réutiliser des propriétés et des setteurs et des getteurs.
    // Cela est utile lorsque vous avec plusieurs entités qui partagent des propriétés communes.

    # Pour utiliser ces deux classes PHP, il vous faudra 2 dépendances PHP de Gedmo : composer require gedmo/doctrine-extensions
    # timestamp : c'est une valeur numérique exprimée en secondes qui représente le temps écoulé (en seconde) depuis le 1er Janv. 1970 00:00


    use TimestampableEntity;
    use SoftDeleteableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text')]
    private $Comment;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'article')]
    private $article;

    public function __construct()
    {
        $this->article = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->Comment;
    }

    public function setComment(string $Comment): self
    {
        $this->Comment = $Comment;

        return $this;
    }

    public function getArticle(): ?self
    {
        return $this->article;
    }

    public function setArticle(?self $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function addArticle(self $article): self
    {
        if (!$this->article->contains($article)) {
            $this->article[] = $article;
            $article->setArticle($this);
        }

        return $this;
    }

    public function removeArticle(self $article): self
    {
        if ($this->article->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getArticle() === $this) {
                $article->setArticle(null);
            }
        }

        return $this;
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Categorie;
use App\Entity\Commentary;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ArticleController extends AbstractController
{
    /**
     * @Route("/voir/{cat_alias}/{artcle_alias}_{id}", name="show_article", methods={"GET"})
     */
    public function showArticle(Article $article, EntityManagerInterface $entityManager): Response
    {
        $commentaries = $entityManager->getRepository(Commentary::class)->findBy(['article' => $article->getId()]);
        return $this->render('article/show_article.html.twig', [
            'article' => $article,
            'commentaries' => $commentaries,

        ]);
    }

    /**
     * @Route("/voir/{alias}/", name="show_articles_from_category", methods={"GET"})
     */
    public function showArticleFromCategory(Categorie $categorie, EntityManagerInterface $entityManager): Response
    {
        $articles = $entityManager->getRepository(Article::class)->findBy(['category' => $categorie->getId(), 'deletedAt' => null]);

        return $this->render('article/show_articles_from_category.html.twig', [
            'articles' => $articles,
            'category' => $categorie,
        ]);
    }
}

templates/article/show_article.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<div class="row">
		<div class="col-12">
			{% include 'include/_flashes.html.twig'%}

		</div>
	</div>
	<div class="row">
		<div class="col-10my-4 mx-auto">

			<div class="card">
				<div class="card-header">
					<h1 class="card-title text-center mb-5">{{article.title}}</h1>
					<p class="h4 text-center mb-3 text-secondary">{{ article.subtitle }}</p>
				</div>
				<ul class="list-group list-group-flush">
					<li class="list-group-item text-center text-muted">Crée le:
						{{ article.createdAt|date('d/m/Y H:i' )}}
						<span class="text-muted">Mis à jour le
							{{ article.updatedAt|date('d/m/Y H:i' ) }}</span>
					</li>
				</ul>
				<img class="img-custom" src="{{ asset ('uploads/') ~ article.photo}}" alt="{{article.title}}">
				<div class="card-body">
					<p class="card-text my-4 col-10 mx-auto">{{ article.content|raw}}</p>
				</div>


			</div>
		</div>
		{% if app.user %}
			{# {{ render(controller('App\Controller\Commentary\Controller::addCommentary', ['id' => article.id])) }} #}

			{{ render(url('add_commentary', {'id': article.id}) ) }}
		{% else %}
			<div class="row">
				<div class="col-8 mx-auto">
					<p class="h4">Vous devez être connecté pour commenter cet article</p>
					<a class="d-block cc=ol-3 btn btn-info mx-auto" href="{{ path ('app_login')}}">Connexion</a>
				</div>
			</div>
		{% endif %}
		<hr>


		<h3>Espace Commentaires</h3>

		{% if commentaries is not null %}
			<div class="row ">
				<div class="col-5">

					{% for commentary in commentaries %}

						{% if commentary.deletedAt is null %}

							<div class="bg-light shadow my-2">

								<p class="ps-3 text-muted">Crée le:
									{{ commentary.createdAt|date('d/m/Y') }}
									| Ecrit par:
									{{commentary.author ? commentary.author.prenom ~ ' ' ~  commentary.author.nom :"Pas d'auteur"}}


									{% if  commentary.author is same.app.user %}

										<span style="float: right" class="pe-2" onclick="return confirm('Voulez-vous archiver ce commentaire? \n\r Vous retrouverez ces commentaires dans la partie Mes commentaires de votre profil.')">
											{# {================1ère FACON=========================}
																																=> suite du commentaire de : CommentarController::SoftDeleteCommentary()
																																Ici nous avons construit,avec le symbole ? dans le 'href' après le {{path()}}, dans notre URL avec les arguments nécessaires pour la redirection (voir CommentaryController)
																																 #}
											{#                                        <a href="{{ path('soft_delete_commentary', {'id': commentary.id}) }}?cat_alias={{ article.category.alias }}&article_alias={{ article.alias }}&article_id={{ article.id }}" class="text-danger"><i class="fa fa-times-circle"></i></a>#}
											{# {=========================================}#}

											{# {# {================2eme FACON=========================}
																						=> Suite du commentaire de : CommentaryController::softDeleteCommentary()
																						Ici nous nous retiré tous paramètres dans l'URL. (excepté le paramète OBLIGATOIRE de la route {id}) #}

												<a href="{{ path('soft_delete_commentary', {'id': commentary.id}) }}" class="text-danger"> <i class="fa fa-times-circle"></i>
											</a>

											{# {=========================================}#}

											<a href="" class="text-danger">
												<i class=" fa fa-times-circle"></i>
											</a>
										</span>
									{% endif %}
								</p>
								<p class="ps-3 ">{{commentary.comment}}</p>
							</div>


						</div>

					</div>


				{% endblock %}

templates/article/show_articles_from_category.html.twig
{% extends 'base.html.twig' %}
{% block body %}

<h1 class="text-center mt-3">{{ category.name|capitalize}}</h1>

{% for article in articles %}

	<div class="row">
		<hr>
		<a href="{{ path ('show_article', {'cat_alias': article.category.alias, 'article.alias':article.alias, 'id': article.id} ) }}" class="text-dark text-decoration-none">
			<div class="col-8 mx-auto">


			{% endfor %}
			<div class="card mb-3" style="max-width: 100%; height:">
				<div class="row g-0">
					<div class="col-md-4">
						<img src="{{ asset ('uploads/') ~ article.photo }}" class="img-fluid rounded-start img-card-custom" alt="{{ article.title }}">
					</div>
					<div class="col-md-8">
						<div class="card-body">
							<h5 class="card-title">{{ article.title|length > 80 ? article.title|slice(0,50) ~ '...' : article.title }}</h5>
							<p class="card-text">{{ article.subtitle|length > 170 ? article.subtitle|slice(0,170) ~ '...' article.subtitle}}</p>
							<p class="card-text">
								<small class="text-muted">Dernière modification :
									{{ article.updatedAt|date('d/m/Y')}}<span class="text-muted">
										|Auteur:
										{{ article.author.prenom }}
										{{ article.author.prenom }}</span>
								</small>
							</p>
						</div>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>
{{% else %}}
<div class="row">
	<div class="mx-auto col-8">
		<p class="alert alert-info text-center">La catégorie
			{{ category.name}}
			ne contient pas encore d'article.</p>
	</div>

</div>{% endfor %}{% endblock %}